---
#

include:
  - /packages/backend/.gitlab-ci.yml
  - /packages/frontend/.gitlab-ci.yml
  - https://raw.githubusercontent.com/SocialGouv/code-du-travail-numerique/douglasduteil/refacto-gitlab-separate-package-installation/.gitlab-ci/extends.yml

  #- /.gitlab-ci/variables.yml
  #- /.gitlab-ci/extends.yml
  #
  #- /.gitlab-ci/stages/prepare.yml
  #- /.gitlab-ci/stages/quality.yml
  #- /.gitlab-ci/stages/register.yml
  #- /.gitlab-ci/stages/notify.yml
  # /.gitlab-ci/stages/deploy.yml

#

stages:
  - "Prepare"
  - "Code Quality"
  - "Registration"
  - "Integration test"
  - "Deploy"
  #- "Notify Finished Deployment"
#

