#

Install frontend:
  extends: .base_yarn_workspace_install
  variables:
    CONTEXT: frontend
  before_script:
    - find packages -maxdepth 1 -type d -not -name frontend | tail -n +2 | xargs rm -rf
  artifacts:
    expire_in: 1 day
    paths:
      - node_modules
      - packages/frontend/node_modules

Lint @domifa/frontend:
  extends: .quality_stage
  allow_failure: true
  image: node:12-alpine
  dependencies:
    - Install frontend
  needs:
    - Install frontend
  script:
    - yarn workspace @domifa/frontend lint
